
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compilador.sintactic;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int ENTER = 11;
  public static final int MENTRES = 22;
  public static final int CONST = 24;
  public static final int COND = 2;
  public static final int LPAREN = 5;
  public static final int SORT = 28;
  public static final int RPAREN = 6;
  public static final int ECOND = 20;
  public static final int AND = 32;
  public static final int IGUAL = 9;
  public static final int OR = 33;
  public static final int BOOL = 23;
  public static final int DIV = 13;
  public static final int numero = 35;
  public static final int MAIN = 17;
  public static final int ID = 36;
  public static final int LECT = 27;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int MUL = 14;
  public static final int COMA = 25;
  public static final int NEWLINE = 16;
  public static final int ADD = 3;
  public static final int NULL = 26;
  public static final int MENOR = 7;
  public static final int MOD = 15;
  public static final int RETORNA = 31;
  public static final int VOID = 30;
  public static final int MENIG = 19;
  public static final int MAYOR = 8;
  public static final int NO = 29;
  public static final int PNTCM = 21;
  public static final int MAYIG = 18;
  public static final int FUNC = 34;
  public static final int LCLAVE = 10;
  public static final int VBOOL = 37;
  public static final int RCLAVE = 12;
  public static final int SUB = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COND",
  "ADD",
  "SUB",
  "LPAREN",
  "RPAREN",
  "MENOR",
  "MAYOR",
  "IGUAL",
  "LCLAVE",
  "ENTER",
  "RCLAVE",
  "DIV",
  "MUL",
  "MOD",
  "NEWLINE",
  "MAIN",
  "MAYIG",
  "MENIG",
  "ECOND",
  "PNTCM",
  "MENTRES",
  "BOOL",
  "CONST",
  "COMA",
  "NULL",
  "LECT",
  "SORT",
  "NO",
  "VOID",
  "RETORNA",
  "AND",
  "OR",
  "FUNC",
  "numero",
  "ID",
  "VBOOL"
  };
}

